"""empty message

Revision ID: 8b423174464d
Revises: 489c0faf1e43
Create Date: 2023-09-04 22:32:11.421861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b423174464d'
down_revision: Union[str, None] = '489c0faf1e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('imgUrl', sa.String(), nullable=False))
    op.add_column('question', sa.Column('userImgUrl', sa.String(), nullable=False))
    op.add_column('question', sa.Column('brandName', sa.String(), nullable=False))
    op.add_column('question', sa.Column('productName', sa.String(), nullable=False))
    op.add_column('question', sa.Column('option', sa.String(), nullable=False))
    op.add_column('question', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('question', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('isPhotoReviewed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'isPhotoReviewed')
    op.drop_column('question', 'price')
    op.drop_column('question', 'date')
    op.drop_column('question', 'option')
    op.drop_column('question', 'productName')
    op.drop_column('question', 'brandName')
    op.drop_column('question', 'userImgUrl')
    op.drop_column('question', 'imgUrl')
    # ### end Alembic commands ###
